FROM node:14.17-alpine

# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./

COPY server ./server
RUN ls -a
RUN npm install
EXPOSE 3001
CMD ["npm","run","dev"]