version: "3.8"

services:
  server:
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - COINMARKETCAP_URL=https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest
      - COINMARKETCAP_KEY=e0b3bc59-b57f-4946-8971-72fea7cd508c
      - MONGODB_URL=mongodb+srv://admin-elvin:Sadiq0507925289nazim_@stock-analysis.nwmoc.mongodb.net/cryptos-analysis?retryWrites=true&w=majority
    networks:
      - backend
      - frontend

  client:
    depends_on:
      - server
    build:
      context: ./client
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend

networks:
  backend:
  frontend:
